#以下是业务自定义的conf区
test_conf01=10000
test_conf02=200
test_conf03="test"
test_conf04=["test0","test1"]

#以下是默认的
[server]
#服务名称
service_name="xxxxx.svc"
http_port="port"
rpc_port="port"

[log]
  logpath="./log"

[[database]]
name="test_mysql"
master="xx.xx.xx.xx:xxxx"
slave="xx.xx.xx.xx:xxxx"
username="username"
password="password"
database="database"
charset="utf8"
parseTime="true"
loc="Local"
readTimeout="2s"
maxIdleConns=2
maxOpenConns=5

[[redis]]
name="test_redis"
addr="ip:port"
max_idle=5
max_idletimeout=300
max_active=100
read_timeout=500
write_timeout=500
slow_time=500
connect_time=500
wait=1

#将从etcd获得的地址轮询访问
[[http_server_client]]
service_name="xxxxxx01.svc"
proto="http"
endpoints_from="etcd"
balancetype="roundrobin"
addr=["127.0.0.1:4015","127.0.0.1:4019"]  #兜底addr
dial_timeout=1000
read_timeout=1000
retry_times=1

#将从ip随机访问
[[http_server_client]]
service_name="xxxxxx02.svc"
proto="http"
endpoints_from="ip"
balancetype="random"
addr=["127.0.0.1:4015","127.0.0.1:4019"]  #兜底addr
dial_timeout=1000
read_timeout=1000
retry_times=1
